<<<<<<< HEAD
version: '3.8'

services:
  floatchat:
    build: .
    ports:
      - "8000:8000"  # Backend API
      - "8501:8501"  # Frontend
    environment:
      - APP_NAME=FloatChat
      - APP_VERSION=1.0.0
      - DEBUG=false
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
=======
version: '3.8'

services:
  floatchat:
    build: .
    ports:
      - "8000:8000"  # Backend API
      - "8501:8501"  # Frontend
    environment:
      - APP_NAME=FloatChat
      - APP_VERSION=1.0.0
      - DEBUG=false
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
>>>>>>> 5347d1d (Initial commit: FloatChat AI-Powered ARGO Data System)
  redis_data: