# Render.com deployment configuration for FloatChat
# Single service deployment using Docker

services:
  - type: web
    name: floatchat
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: APP_NAME
        value: FloatChat
      - key: APP_VERSION
        value: 1.0.0
      - key: DEBUG
        value: false